---
title: "Problem Set 3: Are Black Legislators Willing to Help African Americans Without Political Incentives?"
due_date: 2023-03-26

---


- Data: [`aa_rep.csv`](/files/data/aa_rep.csv)

Due: March 26th 2023


## Background

This study conducts a randomized field experiment that examines whether African American politicians are more intrinsically motivated to support African American.

> This exercise is based on: Broockman, D. E. 2013. “[Black Politicians Are More Intrinsically Motivated to Advabce Blacks' Interests: A Frield Experiment Manipulating Political Incentives.](https://onlinelibrary.wiley.com/doi/epdf/10.1111/ajps.12018)” *American Journal of Political Science* 

Broockman conducts a field experiment involving about 7,000 state legislators. Using a putatively black alias, he sent an email asking for help signing up for state unemployment benefits. In the email, the key difference is whether the sender lives within or far from each legislator's district; the legislator has a more political incentive to respond to the ones within the jurisdiction. 

To put it simple, Broockman examines whether African American politicians are more likely to respond to the request from an African American even if he is not residing within their jurisdiction. 


The names and descriptions of variables in the data set `aa_rep.csv` are:


-------------------- ----------------------------------------------------------
 Name                 Description
-------------------- ----------------------------------------------------------
 `response`           Response from the legislator=1, otherwise=0
 `treat_out`          Residing outside the district (treatment; 1) or within the district (control; 0)

 `leg_race`           Race of legislator; white=1, black=2, latino=3, native american=4, arab=5, asian=6
 `leg_democrat`       Partisanship; Democrat=1, otherwise=0
 `leg_state`          State of legislator  
 `leg_gen`            Gender of legislator (female=1; otherwise=0)
 ------------------------------------------------------------------------------

## Question 1 

Load the `tidyverse` package in the setup chunk. Read the data `"aa_rep.csv"` into R using `read_csv`. How many observations are in the dataset? After that, create a table that includes average values for all binary variables (such as `treat_out`, `leg_democrat`, `response`, and `leg_gen`) with `knitr::kable()` to produce a nice looking table. Describe each variable in the table in a plain language. For example, how many female legislators are included in the sample (the proportion)? What percentages of legislators replied to the email request? 


## Question 2

In the previous question, we left out `leg_race`. Let's look at how many legislators are in the dataset by race in treatment and control groups. Create a nice looking table that shows racial categories in rows and experimental conditions in columns. 


## Question 3

The benefit of randomly assigning individuals to the treatment or control groups is that the two groups would have similar characteristics in terms of pre-treatment variables, on average. 

First, let's create a new binary variable (or vector) for African American legislators, called `leg_black` indicating black=1 (otherwise=0).

Second, using the `group_by` and `summarize` functions, create a tibble called `balance_table` that shows the proportion of African American, Democrat, and women legislators between treatment and control groups in the dataset (calculating the average values). Then use the `knitr::kable()` function to create a nice-looking table, including some informative column names. Briefly comment on the whether you think these variables appear balanced. If balanced, what does this mean? If not balanced, what should we do?

## Question 4

Before answering some of the research questions, now you are wondering legislators in which states are the most responsive. Let's calculate the average response rates by states first and then create a bar plot with decending order.


## Question 5

One of the questions that can be answered with the data is whether legislators would be more (or less) responsive if the email request is from the same district where legislators work (other districts that are away from their jurisdictions).

To answer this question, we can calculate the SATE (Sample Average Treatment Effects) using the following two variables: `response` and `treat_out`. 

Do legislators respond to the unemployment benefit request more if the email sender lives within the district?  

## Question 6

Describe, in words, what the  outcomes are in the analysis for the last problem. Substantively, what does the fundamental problem of causal inference refer to in this context? Make sure to refer to what treatment and control means in this experiment rather than just mention the "treatment" and "control" groups.

## Question 7

The email sender name signals the legislators his race. In this question, we would like to know whether African American legislators are more likely to respond to the request even if the sender lives in outside their jurisdiction compared to all other legislators [`leg_black`].

## Question 8 [optional]

Now we are sort of wondering whether other legislators, especially racial minorities, would be willing to help the request from an African American. Let's calculate the SATE by race of legislators and create a `tibble` table (the nice looking one). The table should be either 2 (treated and control) x 6 (each race) or 6x2. 

Once you calculate SATEs by race of legislators, then, create a bar plot using the table. The figure should depict the bars by ascending order. You can choose your own color for the bar plot!  

