---
title: "Prediction: Elections and Regression"
date: 2023-04-05
---


## Readings 

- For prediction and loops, see QSS  4.1 (you can skip 4.1.1)
- For regression, see either MD Ch 5 or QSS 4.2 (you can skip 4.2.5). 

## Data

- Reinstall the TPDdata package that has new data for this week:
```{r}
#| eval: false
remotes::install_github("seungho-an/TPDdata")
```

<!-- - If you cannot install the package, you can download the data locally at -->
<!--   - [`poll20.csv`](/files/data/polls20.csv) -->
<!--   - [`pres20.csv`](/files/data/pres20.csv) -->
<!--   - [`national_poll20.csv`](/files/data/national_polls20.csv) -->

<!-- ```{r} -->
<!-- #| eval: false -->
<!-- library(tidyverse) -->
<!-- polls20 <- read_csv("polls20.csv") -->
<!-- pres20 <- read_csv("pres20.csv") -->
<!-- national_polls20 <- read_csv("national_polls20.csv") -->
<!-- ``` -->

- You may need to install the `lubridate` and `broom` packages if it's not installed:
```{r}
#| eval: false
install.packages("lubridate")
install.packages("broom")
```

## Slides 

<!-- - Tuesday (10/11) lecture: Prediction and loops -->
<!--   - [PDF of slides as I present them](/slides/12_prediction_loops.pdf) -->
<!--   - [PDF of handout version of slides](/slides/12_prediction_loops_handout.pdf) (no incremental slides) -->

<!-- - Tuesday (10/13) lecture: Regression -->
<!--   - [PDF of slides as I present them](/slides/13_regression.pdf) -->
<!--   - [PDF of handout version of slides](/slides/13_regression_handout.pdf) (no incremental slides) -->
